### PR TITLE
Another example on websocket with event

### PR DESCRIPTION
**Pull request by leandrosilva**
Hello. I'm intending to use misultin in a WebSockets-based application, and because of this, I wrote an another example on websocket with event just to prove a concept. I think it may be useful to others. If you think so as well, I'd be pretty happy on you accept this pull-request.

Thank you!

### CODE REVIEW

**Comment by ostinelli** [comment]
hi leandro!

only difference is specifying in an input box the data sent over to server, can you please tell me why you think this is more valuable in showing misultin's websocket support?

**Comment by leandrosilva** [comment]
I didn't think it's more valuable. Both are valuable, in my opnion. But I think that this second one (that yes, is just a "patch" on the first - it's why I added "2" as suffix) is interesting to show in a more didactic the events that goes happening while the client interacts with the server.

**Comment by ostinelli** [comment]
thank you leandro, will consider a future addition.

**Comment by ostinelli** [comment]
will be pushing your example today. thank you.

**Pull request closed without merging**
