### PR TITLE
Added .gitignore and allow to send file with custom headers.

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
If I am serving assets, I would like to set far away Expires header. Otherwise yslow! will keep yelling at me! :) Thanks for the quick reply!

PS: The .gitignore commit is not important, just a convenience.

**Comment by josevalim** [comment]
Btw, the Expires header is just an example of why you would want to set headers when sending a file. Is there a reason for not allowing it in misultin?

**Comment by ostinelli** [comment]
Ok, accepted. Will pull asap.

**Comment by ostinelli** [comment]
pushed. thank you.

**Pull request closed without merging**
