### PR TITLE
Websocket parser refactor

### PR DESCRIPTION
**Pull request by RJ**
I refactored the websocket frame/parsing code in hybi-10, I hope it will be easier to follow, and to extend to support websocket protocol extensions later.

It should also handle fragmented messages with control messages mixed in now, although I can't find a client in the wild that will send fragmented messages, so haven't really tested that bit.

Would be good to get some feedback :)
(not expecting a merge atm, using this pull request for discussion)

Cheers,
RJ

cc @dbudworth

### CODE REVIEW

**Comment by RJ** [comment]
Oh, whoops, ignore the PROXY protocol commit, just looking for feedback on the websocket one

**Comment by ostinelli** [comment]
Hi RJ,

this looks really nice. FYI, this weekend I've planned to bring misultin close to a 0.9 release. I'll wait for this issue to be fully solved before I do though.

It'd be nice to find a library that could actually test the fragmented support implementation, this could also be added in the integration tests, which currently only test for a previous websocket release.

I'll take a deeper look at this during the weekend.

r.

ps: @awsong if you feel like telling your opinion, please do so! ^^_

**Comment by ostinelli** [comment]
btw, out of curiosity why hybi-10 and not 17? :)

**Comment by RJ** [comment]
Hybi-17 is just a copy paste of hybi-10, with the version bumped and a header check removed. I worked on -10 because that's what the version of chrome on my desktop uses.

I'd like to find a way to share the majority of the code between -10 and -17. Perhaps extract some out to a shared module, or make one module handle both. Any thoughts on the best way to do that?

**Comment by ostinelli** [comment]
sure, refactoring to DRY is simple to do.

i'm more interested in bringing the code you submitted to master, it's the first code i see that supports segments :)

**Comment by RJ** [comment]
ok, i'm away in germany atm, back home tomorrow (monday) night. I'll be pushing this live to irccloud this week, will let you know how it goes. provided it works as expected, i'll dry out hybi 17 and it should be safe to roll a new misultin release :) 

do you know of any decent websocket client that can do multiple versions, to aid testing this stuff?

**Comment by ostinelli** [comment]
i've refactored your code and set a common module for protocols 10 and 17. you can find it in the dedicated branch:
https://github.com/ostinelli/misultin/tree/ws-refactor

branch 'dev' does not exist anymore, everything else except this commit has been pushed to 'master'.

let me know what do you think.

ps: unfortunately no, i do not know a comprehensive library for testing purposes.

**Comment by RJ** [comment]
Cool, I pushed a couple of minor tweaks, and added a max unparsed frame size:
    https://github.com/RJ/misultin/commits/ws-refactor

**Comment by RJ** [comment]
Pushed my fork of ws-refactor live to irccloud just now then rolled it back.
Looks like the hybi stuff and proxy support all worked fine, but hixie-76 is broken, seeing these errors:

```
=ERROR REPORT==== 22-Nov-2011::12:24:00 ===
        module: misultin_server
        line: 216
http process <0.12776.0> has died with reason: {badarg,
                                            [{erlang,byte_size,
                                              [[223,155,227,53,25,19,77,
                                                231]]},
                                             {'misultin_websocket_draft-hixie-76',
                                              handshake,3},
                                             {misultin_websocket,connect,
                                              4},
                                             {misultin_acceptor,
                                              open_connections_switch,8}]}, removing from references of open connections
```

Not sure which browsers still use hixie-76, but the popular flash websocket alternative uses hixie-76, and that was causing a fair amount of errors.

**Comment by RJ** [comment]
This was caused by the code reading the PROXY line leaving the socket options set to list, but hixie-76 (and possibly other places) expected binary.

Fixed in https://github.com/RJ/misultin/commit/839137d7a51e14c81f6c86e00ea9a4e1b8ade38f

**Comment by ostinelli** [comment]
indeed. will check implications of this asap and proceed.

i don't think it's necessary to do all this: probably at this stage the inet options are the default ones, and are probably best hard-coded instead of saved and retreived. i will check for this and provide a patch based on yours. unless you feel curious and want to provide it yourself: i'll probably be unable to look into this for some days unfortunately. ^^_

thank you,

r.

**Comment by RJ** [comment]
ok - wasn't sure whether to do this or not - i suppose misultin has no reason to change the options before this point anyway..
I'll update it to use hardcoded values

**Comment by RJ** [comment]
Changed to restore hardcoded socket options:   https://github.com/RJ/misultin/commit/d0f5c612056ceaae2c6025bad668456aabbba23e

There's also a websocket example app in examples/websocket in my branch. I made an app so that I could use rebar to pull in erlflashpol dep, to test the flash websocket fallback (which needs a flash policy server running on port 843).

**Comment by ostinelli** [comment]
perfect. yes, saw the websocket apps, however i prefer to have those in the test, so i'll skip them for now ^^_

could you please however provide a pull request for all of your work? i like most of it, and in this way we can keep track of your history too.

thank you :)

r.

**Comment by RJ** [comment]
Sure, what do you want exactly - a pull request to master with everything in my ws-refactor except the websocket app?

**Comment by ostinelli** [comment]
yep! :)

thank you.

**Comment by RJ** [comment]
Here it is: https://github.com/ostinelli/misultin/pull/74

this pull request is now redundant

**Pull request closed without merging**
