### PR TITLE
Fixing issue 38 (multiple misultines in one node)

### PR DESCRIPTION
**Pull request by si14**
I've done my best to keep your coding style untouched. But if you don't mind I'll make a bit of refactoring in another pull request — at least adding type specs for dialyzer, rebaryzing and applying 80 columns rule.

### CODE REVIEW

**Comment by ostinelli** [comment]
thank you, merged.

**Comment by ostinelli** [comment]
had to reopen, github is performing weirdly today.

**Comment by ostinelli** [comment]
don't like the idea of having the RFC ets table owned by one of the misultin servers though. what if one server crashes? the second one wouldn't have an RFC table anymore. so i'm gonna refactor this to allow for multiple RFC ets tables as well.

**Comment by si14** [comment]
I think the better solution is to make RFC table be owned by supervisor. I thought that it is meaningful to have a shared RFC table.

**Comment by ostinelli** [comment]
you will still have one supervisor for every instance of misultin that you start, so the issue would remain.

just pushed what i believe to be the best way to handle it.

**Comment by si14** [comment]
Yes, you are right. Thank you.

**Pull request merged**
