### PR TITLE
Porting Unix/OSX build to use rebar

### PR DESCRIPTION
**Pull request by kevsmith**
If you're interested, this pull request includes a recent rebar script, rebar.config, and ports the Makefile to use rebar for the build. All targets except for 'make debug' were kept intact.

### CODE REVIEW

**Comment by ostinelli** [comment]
hi kev,

thank you for this. i'm thinking to add rebar, though i do not want to force a dependency and i'm therefore building a script which falls back to normal makefile without rebar if the latter is not available.

trying to figure out how to pass macro values with rebar [like erlc -Dmacro], once this is done i should be able to release it adding your pull too.

**Comment by ostinelli** [comment]
hi again kev,

to make this work i need to be able to pass a macro variable at compile time, which specifies the level of logging in the application. in rebar, this can only be done using a .config file, and thus i would need to start adding multiple rebar config files to support this, and it's something i don't want to do right now.

i'd love to have some feedback on this, but this hasn't happened yet even on a similar request https://github.com/ostinelli/misultin/pull/23, so for now rebar won't be added.

i leave this request open for further eventual comments.

again, thank you.

r.

**Comment by joewilliams** [comment]
@ostinelli FWIW I would love to see misultin use rebar, I'm on the rebar commit team so I might be a bit bias.  Point me in the right direction and I'll see if I can come up with a decent config solution.

**Comment by ostinelli** [comment]
Hi Joe.

misultin's logging is taken care of through macros which call the error_logger in ways similar to:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-define(LOG_INFO(Str, Args),
    erlang:apply(error_logger, info_msg,
        [lists:concat(["    module: ", ?MODULE, "~n line: ", ?LINE, "~n", Str, "~n"]), Args]
    )).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

There are 4 logging macros: LOG_DEBUG, LOG_INFO, LOG_WARNING and LOG_ERROR.

This is pretty handy as I can put anywhere in my apps the macros like this:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
?LOG_INFO("Application started with pid ~p", [self()]).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

However, problems arise when I want to specify a logging level in my application. The way I currently do this is to set a macro variable at compile time which changes the way the logging macros are defined.

For instance, if I compile with "erlc -D log_debug ..." all of the 4 logging macros get defined with calls to the erlang_logger; if I compile with "erlc -D log_error" then only the LOG_ERROR macro gets defined as a call to the error_logger, the other 3 macros get simply defined like this:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-define(LOG_DEBUG(Str, Args), ok).
-define(LOG_INFO(Str, Args), ok).
-define(LOG_WARNING(Str, Args), ok).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Now, having it this way sure has the advantage of keeping things very simple and macro can propagate in the code in the most easy way.

This has the disadvantage that you need to re-compile misultin whenever you need to change the log level. It's a bit weird indeed, but so far it's the best option that I found.

So for this to work I need to pass a variable to rebar at compile time, such as 'rebar -D log_info ...' which AFAIK cannot be done. Can it?

PS: I'm thinking alternatives.

One is to have a logger for every instance of misultin but this wouldn't work, since then you would need to pass over the logger's gen_server pid everywhere you call a log function (might work if you keep it in your core).

Another is to have a single logger instance per node so that you can register a name [misultin_logger], but this calls for troubles since you have to decide which of misultin instances is supervising the logger: and what happens in this case if the instance which handles the logger goes down?

Any input is warmly welcome.

**Comment by RJ** [comment]
I would absolutely depend on rebar. 
Just have a Makefile that calls rebar, so people can type "make".
It's the defacto build system now by far, apart from really ancient large codebases like ejabberd/rabbit. 
Every time I have to use an erlang app that doesn't use rebar it puts me in a bad mood.

People are accustomed to using rebar to manage deps too, so you could consider using lager for all your logging needs (via a rebar dep). On the other hand, it may well be best to leave the fancy logging up to the app that is using misultin, and keep misultins logging mainly for debugging purposes, in which case compile-time macros to change it is perfect, imo. (even if that means uncommenting lines in the rebar.config)

**Comment by ostinelli** [comment]
hi RJ, thank you for this nice input. it's convincing, and will be adopted.

only thing missing IMHO is the access log, which has to be passed back via a fun to the application so that it can use it in its own logging logic.

will implement it asa i finish implementing sessions.

**Comment by joewilliams** [comment]
Woot! +1 Let me know if I can help.

**Comment by ostinelli** [comment]
parametrized access log added:
https://github.com/ostinelli/misultin/blob/dev/examples/misultin_access_log.erl

amongst other things considerably reduced [around 40-45%] memory usage, and added session variables:
https://github.com/ostinelli/misultin/blob/dev/examples/misultin_sessions_example.erl

i'm on my way to 'rebarize' it. joe, can you please take a look when i'm done to see if you can in any way improve my rebar config / makefile script.

also, what about windows?

**Comment by ostinelli** [comment]
joe,

misultin is now 'rebarized', as you can see from:
https://github.com/ostinelli/misultin/blob/dev/Makefile

what i don't like/understand:
1. to compile with a macro, i basically dump a rebar.config file so that i can specify the macro {d, log_debug} ad erl_opts parameter. can this be done otherwise?
2. the commands 'rebar dialyze', 'rebar check-plt', 'rebar build-plt' all respond to me:
   `Command 'dialyze' not understood or not applicable`
3. can this be used in windows too?

can you please point me in the right direction to finalize this file?

thank you.

r.

**Comment by joewilliams** [comment]
1) At one point I had a patch to rebar that allowed you to specify erl_opts on the command line as a global variable. I don't think it ever made it into mainline. What you are currently doing in the makefile looks reasonable enough to me but obviously suboptimal. @dizzyd any ideas on how to improve this sort of situation in rebar?

2) A few months back we remove dialyzer support from rebar, the dialyzer command is much more robust and rebar's support wasn't all that ideal in a lot of situations.

3) rebar supports windows, recently there were even start scripts added to the rebar git repo.

**Comment by ostinelli** [comment]
1. i'd love to have erl_opts passed in command line. let's see if @dizzyd has any idea on how to improve this.
2. ok, no dialyzer through rebar, added a commodity line in make
3. nice, i'll have to look into it [haven't booted erlang in windows in quite some time now].

**Comment by kevsmith** [comment]
Sent from my iPhone. Please excuse terse or misspelled responses.

On Sep 16, 2011, at 12:39, Roberto Ostinelli reply@reply.github.com wrote:

> joe,
> 
> misultin is now 'rebarized', as you can see from:
> https://github.com/ostinelli/misultin/blob/dev/Makefile
> 
> what i don't like/understand:
> 1. to compile with a macro, i basically dump a rebar.config file so that i can specify the macro {d, log_debug}. can this be done otherwise?
> 2. the commands 'rebar dialyze', 'rebar check-plt', 'rebar build-plt' all respond to me:
>    `Command 'dialyze' not understood or not applicable`

I believe dialyzer integration was removed this past summer :(

**Comment by ostinelli** [comment]
hi @kevsmith,

yes that had been cleared out by @joewilliams :)

joe, do you happen to have any news regarding this, as i did not see dizzyd pop in. otherwise i'll just think of this as finalized.

**Comment by joewilliams** [comment]
I don't unfortunately. I would just go with what you have and if need be we could add it later.

**Comment by ostinelli** [comment]
ok then,

i'll consider this pull request _accepted_ and i close it.

thank you!

r.

**Comment by kevsmith** [comment]
Sorry. Some delayed email craziness on my end.

**Comment by ostinelli** [comment]
eheh i guessed so.

**Pull request closed without merging**
