### PR TITLE
No artificial headers count limitation

### PR DESCRIPTION
**Pull request by yrashk**

### CODE REVIEW

**Comment by nox** [comment]
+1

**Comment by omarkj** [comment]
+1

**Comment by ostinelli** [comment]
leaving out artificial headers count limitation is a total security risk. a malicious client can simply keep on sending headers forever, until memory runs out and the erlang VM crashes.

**Comment by yrashk** [comment]
lets make it configurable?

**Comment by ostinelli** [comment]
i think users should really be aware of this, and if there's such a need they'd be better off in changing the MACRO value to something very big or remove the code by themselves. just to stay on the safe side.

btw: yaws and mochi both have this limitation, and there's a perfectly good reason for that.

**Comment by yrashk** [comment]
I understand.

**Comment by ostinelli** [comment]
as discussed, this will stay as macro. closed.

**Pull request closed without merging**
