### PR TITLE
Added "Last-Modified" header for file response.

### PR DESCRIPTION
**Pull request by davidgaleano**
Hi,

As part of my Erlang learning I have modified misultin reqt to have a "Last-Modified" header for file responses. 

I have also changed FILE_READ_BUFFER to be a multiple of 1024 instead of 1012, because that is the value for 1 KB that I use, not sure about your original intentions...

Regards.

### CODE REVIEW

**Comment by ostinelli** [comment]
hi!

shouldn't this be used in conjunction with a "304 Not Modified" response? otherwise what could be the use of it?

**Comment by davidgaleano** [comment]
I guess so, I was just changing the code to learn Erlang and thought you may want to use it.
I will try changing the code to return 304s.

**Comment by davidgaleano** [comment]
I added handling of "If-Modified-Since" to return 304s for an exact match of our "Last-Modified", this is what nginx does by default.

**Comment by ostinelli** [comment]
for some reason i was unable to merge, so i had to manually patch.

added, thank you 3b669510531038ca298cad61e6023706c0f29c4f

**Comment by davidgaleano** [comment]
OK, but without the Expires header the browsers caching of the file is a bit undefined, some of them will decide to not even ask for the file again for a while, that is the reason I was expiring the file immediatelly, to force the browser to ask again for the file.
My next suggestion was going to be to add an extra parameter to make the expire time configurable depending on the file path; that is what we do for our site, different files have different times to expire.
Btw, just wondering about the value for FILE_READ_BUFFER, is 1012 a typo for 1024?
I guess using "case" is more Erlang than my attempt at using "if" :-)
Regards.

**Comment by ostinelli** [comment]
point taken, committed 170da462ba8f5887e5639f37163d91dd84f4b4fb

typo corrected. thank you.

**Pull request closed without merging**
