### PR TITLE
misultin_http:socket_loop together with socket.io-erlang

### PR DESCRIPTION
**Pull request by fgc**
The pattern for reqinfo, session_cmd and body_recv calls in socket_loop should match the calling pid, not the LoopPid. Otherwise it never matches, and anyways we need the socket pid for the response.

### CODE REVIEW

**Comment by ostinelli** [comment]
i'm sorry, but i think you're missing the point. `socket_loop` manages the developer's `handle_http` process running in LoopPid and thus it only should accept messages from LoopPid. also, LoopPid is the pid that `socket_loop` only has to respond to (aka the caller): this is intended behavior, and the pattern matching you are trying to remove actually prevents `socket_loop` from receiving unwanted messages from other processes.

as you can easily see from misultin examples, these do work... if what you say were true, many of misultin functionalities simply wouldn't.

thus: is there a particular user-case you have seen a bug in this behavior? if so, please report it because as per now, this is an invalid bug report.

**Comment by fgc** [comment]
I guess yrashk/socket.io-erlang, which is what I was trying to get going is bypassing the misultin api and issuing direct messages somewhere. Their demo worked just fine with misultin 0.8 and now fails to connect unless I make the changes I proposed.

**Comment by ostinelli** [comment]
I dont' know what @yrashk is doing: let's see if he has some inside information he'd like to share :)

btw: 0.8 didn't have reqinfo, session_cmd and body_recv calls at all as you can see from:
https://github.com/ostinelli/misultin/blob/misultin-0.8/src/misultin_http.erl#L485

**Comment by yrashk** [comment]
I haven't tested socket.io-erlang with any new misultins

**Comment by ostinelli** [comment]
thank you @yrashk.

FYI misultin 0.9 currently is in RC1. a few minor adjustments but it should be soon pushed as 0.9.

i close this pull request for now, as explained here above.

**Comment by yrashk** [comment]
I'd be interested in hearing from @fgc, how exactly does socket.io-erlang fail with the newest misultin. Don't have much time on my hands, though.

**Comment by ostinelli** [comment]
me too, actually, since as previously stated that part for which the patch is proposed wasn't even included in v0.8.

it'd be nice to have a user-case to reproduce the error you are experiencing, @fgc. by the way, which is the error you are experiencing? any console output when running misultin in debug mode?

ps: reopened pull request for ongoing discussion and renamed the issue more appropriately to the content.

**Comment by fgc** [comment]
I had been playing with socket.io-erlang a few weeks ago, but wanted to start anew, so I did:

`rm -rf socket.io-erlang`

`git clone https://github.com/yrashk/socket.io-erlang`

`cd socket.io-erlang`

`make`

(lots of compilation stuff including pulling and compiling the latest commit of misultin)

`cd demo`

`./demo.erl`

Then I connected lo localhost:7878 using Chrome 15.0.874.121, and got:
`
=ERROR REPORT==== 27-Nov-2011::23:27:34 ===
    module: misultin_http
    line: 690
received unexpected message in socket_loop: {<0.59.0>,{reqinfo,headers}}, ignoring`

**Comment by ostinelli** [comment]
do you know what was running with pid `<0.59.0>`?

**Comment by ostinelli** [comment]
Ok I see your point. probably `handle_http` implementation is spawning another process which is then using the Req to get info on it.

I'll accept this pull request. thank you.

**Comment by ostinelli** [comment]
patched, please let me know if this now works for you too.

**Comment by fgc** [comment]
Works fine now, thanks!

**Pull request merged**
