### PR TITLE
Fixes problem with keep_alive and binary mode

### PR DESCRIPTION
**Pull request by omarkj**
Hey,

I created an issue, #34. This provides a fix for that.

The problem was that for keep_alive requests the binary mode was not being carried over to a new request loop.

### CODE REVIEW

**Comment by omarkj** [comment]
Sorry, I see I forgot to rebase the commits. If you want me to squish them into one let me know.

**Comment by ostinelli** [comment]
oh my. cross-working here, i've already provided the patch too ;)

let me know if this is ok for you too.

thank you,

r.

**Comment by omarkj** [comment]
Excellent, works great!

**Comment by ostinelli** [comment]
:)

**Pull request closed without merging**
